postgresql:
  fullnameOverride: postgresql
  primary:
    service:
      type: NodePort
      nodePorts:
        postgresql: 30432

server:
  env:
    JWT_ACCESS_TOKEN_SECRET: lz4.'V+O$.ZKo$uZeA+Ns
    JWT_ACCESS_TOKEN_EXPIRATION_TIME: 86400 # 1d

    JWT_REFRESH_TOKEN_SECRET: 4NN.Gn[avI4EH&R]kX'K{
    JWT_REFRESH_TOKEN_EXPIRATION_TIME: 604800 # 7d

    JWT_VERIFICATION_TOKEN_SECRET: 6aa45!z!;TQ3=%K3$B04I
    JWT_VERIFICATION_TOKEN_EXPIRATION_TIME: 1d

    SMTP_SERVER: gmail
    SMTP_USERNAME: ****
    SMTP_PASSWORD: ****
