POST localhost:4000/register
content-type: application/json

{
  "email": "ludinhquan@gmail.com",
  "password": "Abc@1234"
}

POST localhost:4000/login
content-type: application/json

{
  "email": "ludinhquan@gmail.com",
  "password": "Abc@1234"
}

POST localhost:4000/logout
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMDlkMGMwNC05NDZmLTRmMWUtODEwOS0zYzUyY2ZiMWUwODgiLCJpc0VtYWlsQ29uZmlybWVkIjpudWxsLCJpYXQiOjE2OTcxMTg4NjksImV4cCI6MTY5NzIwNTI2OX0.5MxYYV1MbRoEEJmL1yrcPBkmRPeVwaqzvCir5tZhnTw

GET localhost:4000/me
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMDlkMGMwNC05NDZmLTRmMWUtODEwOS0zYzUyY2ZiMWUwODgiLCJpc0VtYWlsQ29uZmlybWVkIjpudWxsLCJpYXQiOjE2OTcxMTg4NjksImV4cCI6MTY5NzIwNTI2OX0.5MxYYV1MbRoEEJmL1yrcPBkmRPeVwaqzvCir5tZhnTw

POST localhost:4000/user/009d0c04-946f-4f1e-8109-3c52cfb1e088
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMDlkMGMwNC05NDZmLTRmMWUtODEwOS0zYzUyY2ZiMWUwODgiLCJpc0VtYWlsQ29uZmlybWVkIjpudWxsLCJpYXQiOjE2OTcxMTg4NjksImV4cCI6MTY5NzIwNTI2OX0.5MxYYV1MbRoEEJmL1yrcPBkmRPeVwaqzvCir5tZhnTw

{
  "name": "Lu Dinh Quan"
}
