POST localhost:4000/register
content-type: application/json

{
  "email": "ludinhquan1@gmail.com",
  "password": "Abc@1234"
}

POST localhost:4000/login
content-type: application/json

{
  "email": "ludinhquan@gmail.com",
  "password": "Abc@1234"
}

POST localhost:4000/logout
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyOGUyZWU5Yi00MDRjLTRiYmEtOTZiZS1kNTFmYjQ5MWIxMjkiLCJpc0VtYWlsQ29uZmlybWVkIjp0cnVlLCJpYXQiOjE2OTcxOTAzNDcsImV4cCI6MTY5NzI3Njc0N30.867TxyE8rYsqUQZ9mWi97Ol8uFpiRpw7qnJUFnRTRR8

GET localhost:4000/me
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyOGUyZWU5Yi00MDRjLTRiYmEtOTZiZS1kNTFmYjQ5MWIxMjkiLCJpc0VtYWlsQ29uZmlybWVkIjp0cnVlLCJpYXQiOjE2OTcxOTAzNDcsImV4cCI6MTY5NzI3Njc0N30.867TxyE8rYsqUQZ9mWi97Ol8uFpiRpw7qnJUFnRTRR8

PATCH localhost:4000/user
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyOGUyZWU5Yi00MDRjLTRiYmEtOTZiZS1kNTFmYjQ5MWIxMjkiLCJpc0VtYWlsQ29uZmlybWVkIjp0cnVlLCJpYXQiOjE2OTcxOTAzNDcsImV4cCI6MTY5NzI3Njc0N30.867TxyE8rYsqUQZ9mWi97Ol8uFpiRpw7qnJUFnRTRR8

{
  "name": "Lu Dinh Quan"
}

POST localhost:4000/reset-password
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyOGUyZWU5Yi00MDRjLTRiYmEtOTZiZS1kNTFmYjQ5MWIxMjkiLCJpc0VtYWlsQ29uZmlybWVkIjp0cnVlLCJpYXQiOjE2OTcxOTAzNDcsImV4cCI6MTY5NzI3Njc0N30.867TxyE8rYsqUQZ9mWi97Ol8uFpiRpw7qnJUFnRTRR8

{
  "oldPassword": "Abc@1234",
  "newPassword": "Abc@1234"
}

POST localhost:4000/email-confirmation/confirm
content-type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1ZGluaHF1YW5AZ21haWwuY29tIiwiaWF0IjoxNjk3MTg5NDMwLCJleHAiOjE2OTcyNzU4MzB9.j_8t_-c87rT5Qg08_cCGBu5ZqxTKqlOhofTlpMbCyZI"
}

POST localhost:4000/email-confirmation/resend-confirmation-link
content-type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyOGUyZWU5Yi00MDRjLTRiYmEtOTZiZS1kNTFmYjQ5MWIxMjkiLCJpc0VtYWlsQ29uZmlybWVkIjp0cnVlLCJpYXQiOjE2OTcxOTAzNDcsImV4cCI6MTY5NzI3Njc0N30.867TxyE8rYsqUQZ9mWi97Ol8uFpiRpw7qnJUFnRTRR8
