FROM node:18.17-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.json ./
COPY ./apps/server ./apps/server
COPY ./packages/core ./packages/core

RUN npm install -g pnpm
RUN pnpm install

RUN pnpm svr prisma:generate

RUN pnpm build:server

EXPOSE 4000

CMD ["pnpm", "svr", "start:prod"]
