apiVersion: v3
name: auth-dashboard
description: A Helm chart for Booking Solution
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: client
    repository: file://charts/server
    version: 0.1.0
    condition: client.enabled
  - name: server
    repository: file://charts/server
    version: 0.1.0
    condition: server.enabled
